{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b9ca8e3-acda-4067-95b0-0b9962c8a6fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from exercise_1 import parse_fasta, discard_ambiguous_seqs, nucleotide_frequencies, map_reads\n",
    "\n",
    "def test_parse_fasta(tmp_path):\n",
    "    # Create a temporary FASTA file\n",
    "    fasta_content = \"\"\">seq1\n",
    "    AGCTAGCTAG\n",
    "    >seq2\n",
    "    CGATCGATCG\n",
    "    \"\"\"\n",
    "    fasta_path = tmp_path / \"test.fasta\"\n",
    "    fasta_path.write_text(fasta_content)\n",
    "\n",
    "    # Run the function\n",
    "    headers, sequences = parse_fasta(str(fasta_path))\n",
    "\n",
    "    # Assert the outputs\n",
    "    assert headers == [\"seq1\", \"seq2\"]\n",
    "    assert sequences == [\"AGCTAGCTAG\", \"CGATCGATCG\"]\n",
    "\n",
    "def test_discard_ambiguous_seqs():\n",
    "    headers = [\"seq1\", \"seq2\", \"seq3\"]\n",
    "    sequences = [\"AGCT\", \"AGXT\", \"ACGT\"]\n",
    "    filtered_headers, filtered_sequences = discard_ambiguous_seqs(headers, sequences)\n",
    "\n",
    "    assert filtered_headers == [\"seq1\", \"seq3\"]\n",
    "    assert filtered_sequences == [\"AGCT\", \"ACGT\"]\n",
    "\n",
    "def test_nucleotide_frequencies(capsys):\n",
    "    sequences = [\"AGCT\", \"AGCT\", \"AAGGTTCC\"]\n",
    "    nucleotide_frequencies(sequences)\n",
    "\n",
    "    captured = capsys.readouterr()\n",
    "    assert \"A :  0.31\" in captured.out\n",
    "    assert \"G :  0.25\" in captured.out\n",
    "    assert \"C :  0.25\" in captured.out\n",
    "    assert \"T :  0.19\" in captured.out\n",
    "\n",
    "def test_map_reads(tmp_path):\n",
    "    # Create temporary query and reference FASTA files\n",
    "    query_content = \"\"\">query1\n",
    "    AGCT\n",
    "    \"\"\"\n",
    "    reference_content = \"\"\">ref1\n",
    "    TTAGCTTTAGCT\n",
    "    >ref2\n",
    "    AGCTAGCTAGCT\n",
    "    \"\"\"\n",
    "    query_path = tmp_path / \"query.fasta\"\n",
    "    reference_path = tmp_path / \"reference.fasta\"\n",
    "    query_path.write_text(query_content)\n",
    "    reference_path.write_text(reference_content)\n",
    "\n",
    "    # Run the function\n",
    "    results = map_reads(str(query_path), str(reference_path))\n",
    "\n",
    "    # Assert the outputs\n",
    "    assert \"query1\" in results\n",
    "    assert \"ref1\" in results[\"query1\"]\n",
    "    assert \"ref2\" in results[\"query1\"]\n",
    "    assert results[\"query1\"][\"ref1\"] == [3, 9]\n",
    "    assert results[\"query1\"][\"ref2\"] == [1, 5, 9]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
